### PR TITLE
Adds confirm modal for publish

### LINKED ISSUE #23: Add confirm modal for publish or unpublish all
When a user clicks publish or unpublish on a map, the desired behavior is for all resource records in ArchivesSpace associated with the map as components to be published or unpublished in AS as well.

A confirm modal needs to be added so that users are aware of this action, and can either confirm or cancel.

### LINKED ISSUE #25: Clear button in arrangement map component modal does not function
When adding an arrangement map component, once a component has been fetched from ArchivesSpace, a `Clear` button appears in the modal. Clicking this button does not cause any change or action. The expected function would be that it clears the component and allows the user to choose a new one.

### PR DESCRIPTION
**Pull request by helrond**
Adds a confirm modal for "Publish" or "Unpublish" which indicates to users that resource records will be published or unpublished in ArchivesSpace.

Also debugs clear button, fixes #25 

**NOTE: merge #22 first, since this is branched from that PR.**

fixes #23

### CODE REVIEW

**Comment by HaSistrunk** [comment]
@helrond did this work for you when you tested? I'm not getting a modal popping up with the Publish or Unpublish buttons

**Comment by HaSistrunk** [comment]
> @helrond did this work for you when you tested? I'm not getting a modal popping up with the Publish or Unpublish buttons

Sorry, I had to rebuild, it's working now. After confirm publish/unpublish, the button is not switching to publish/unpublish without a page refresh. Also, the modal titles need an update to something like "Confirm publish" and "Confirm unpublish".

**Comment by helrond** [comment]
@HaSistrunk the button is switching for me; it may be there's something cached locally for you? I'd make sure you've brought everything down properly (docker-compose down -v) and then try restarting. I'm not able to reproduce that on my end...

**Comment by HaSistrunk** [comment]
Yep, you're right. It's all working for me now!

**Pull request merged**
